// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(MelanCoreFFIFFI)
    import MelanCoreFFIFFI
#endif

private extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_melan_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_melan_ffi_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return try Data(readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

public protocol MelanEngineProtocol: AnyObject {
    func addLassoPoint(x: Double, y: Double) -> [RenderCommand]

    func addPoint(x: Double, y: Double, pressure: Double, timestamp: Double) -> [RenderCommand]

    func beginLasso(x: Double, y: Double) -> [RenderCommand]

    func beginLassoDrag(x: Double, y: Double) -> [RenderCommand]

    func beginStroke(x: Double, y: Double, pressure: Double, timestamp: Double) -> [RenderCommand]

    func cancelLasso() -> [RenderCommand]

    func clearAll() -> [RenderCommand]

    func endLasso() -> [RenderCommand]

    func endLassoDrag() -> [RenderCommand]

    func endStroke() -> [RenderCommand]

    func fullRender() -> [RenderCommand]

    func getState() -> EngineState

    func hasSelection() -> Bool

    func lassoDelete() -> [RenderCommand]

    func lassoDuplicate() -> [RenderCommand]

    func load(data: Data) throws

    func pan(dx: Double, dy: Double) -> [RenderCommand]

    func redo() -> [RenderCommand]

    func resetViewport() -> [RenderCommand]

    func save(format: SaveFormat) throws -> Data

    func setBrush(config: BrushConfig)

    func undo() -> [RenderCommand]

    func updateLassoDrag(x: Double, y: Double) -> [RenderCommand]

    func zoom(factor: Double, focalX: Double, focalY: Double) -> [RenderCommand]
}

open class MelanEngine:
    MelanEngineProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_melan_ffi_fn_clone_melanengine(self.pointer, $0) }
    }

    public convenience init(canvasSize: CanvasSize) {
        let pointer =
            try! rustCall {
                uniffi_melan_ffi_fn_constructor_melanengine_new(
                    FfiConverterTypeCanvasSize.lower(canvasSize), $0
                )
            }
        self.init(unsafeFromRawPointer: pointer)
    }

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_melan_ffi_fn_free_melanengine(pointer, $0) }
    }

    public static func newA4() -> MelanEngine {
        return try! FfiConverterTypeMelanEngine.lift(try! rustCall {
            uniffi_melan_ffi_fn_constructor_melanengine_new_a4($0
            )
        })
    }

    open func addLassoPoint(x: Double, y: Double) -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_add_lasso_point(self.uniffiClonePointer(),
                                                                   FfiConverterDouble.lower(x),
                                                                   FfiConverterDouble.lower(y), $0)
        })
    }

    open func addPoint(x: Double, y: Double, pressure: Double, timestamp: Double) -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_add_point(self.uniffiClonePointer(),
                                                             FfiConverterDouble.lower(x),
                                                             FfiConverterDouble.lower(y),
                                                             FfiConverterDouble.lower(pressure),
                                                             FfiConverterDouble.lower(timestamp), $0)
        })
    }

    open func beginLasso(x: Double, y: Double) -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_begin_lasso(self.uniffiClonePointer(),
                                                               FfiConverterDouble.lower(x),
                                                               FfiConverterDouble.lower(y), $0)
        })
    }

    open func beginLassoDrag(x: Double, y: Double) -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_begin_lasso_drag(self.uniffiClonePointer(),
                                                                    FfiConverterDouble.lower(x),
                                                                    FfiConverterDouble.lower(y), $0)
        })
    }

    open func beginStroke(x: Double, y: Double, pressure: Double, timestamp: Double) -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_begin_stroke(self.uniffiClonePointer(),
                                                                FfiConverterDouble.lower(x),
                                                                FfiConverterDouble.lower(y),
                                                                FfiConverterDouble.lower(pressure),
                                                                FfiConverterDouble.lower(timestamp), $0)
        })
    }

    open func cancelLasso() -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_cancel_lasso(self.uniffiClonePointer(), $0)
        })
    }

    open func clearAll() -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_clear_all(self.uniffiClonePointer(), $0)
        })
    }

    open func endLasso() -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_end_lasso(self.uniffiClonePointer(), $0)
        })
    }

    open func endLassoDrag() -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_end_lasso_drag(self.uniffiClonePointer(), $0)
        })
    }

    open func endStroke() -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_end_stroke(self.uniffiClonePointer(), $0)
        })
    }

    open func fullRender() -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_full_render(self.uniffiClonePointer(), $0)
        })
    }

    open func getState() -> EngineState {
        return try! FfiConverterTypeEngineState.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_get_state(self.uniffiClonePointer(), $0)
        })
    }

    open func hasSelection() -> Bool {
        return try! FfiConverterBool.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_has_selection(self.uniffiClonePointer(), $0)
        })
    }

    open func lassoDelete() -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_lasso_delete(self.uniffiClonePointer(), $0)
        })
    }

    open func lassoDuplicate() -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_lasso_duplicate(self.uniffiClonePointer(), $0)
        })
    }

    open func load(data: Data) throws { try rustCallWithError(FfiConverterTypeMelanCoreError.lift) {
        uniffi_melan_ffi_fn_method_melanengine_load(self.uniffiClonePointer(),
                                                    FfiConverterData.lower(data), $0)
    }
    }

    open func pan(dx: Double, dy: Double) -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_pan(self.uniffiClonePointer(),
                                                       FfiConverterDouble.lower(dx),
                                                       FfiConverterDouble.lower(dy), $0)
        })
    }

    open func redo() -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_redo(self.uniffiClonePointer(), $0)
        })
    }

    open func resetViewport() -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_reset_viewport(self.uniffiClonePointer(), $0)
        })
    }

    open func save(format: SaveFormat) throws -> Data {
        return try FfiConverterData.lift(rustCallWithError(FfiConverterTypeMelanCoreError.lift) {
            uniffi_melan_ffi_fn_method_melanengine_save(self.uniffiClonePointer(),
                                                        FfiConverterTypeSaveFormat.lower(format), $0)
        })
    }

    open func setBrush(config: BrushConfig) { try! rustCall {
        uniffi_melan_ffi_fn_method_melanengine_set_brush(self.uniffiClonePointer(),
                                                         FfiConverterTypeBrushConfig.lower(config), $0)
    }
    }

    open func undo() -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_undo(self.uniffiClonePointer(), $0)
        })
    }

    open func updateLassoDrag(x: Double, y: Double) -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_update_lasso_drag(self.uniffiClonePointer(),
                                                                     FfiConverterDouble.lower(x),
                                                                     FfiConverterDouble.lower(y), $0)
        })
    }

    open func zoom(factor: Double, focalX: Double, focalY: Double) -> [RenderCommand] {
        return try! FfiConverterSequenceTypeRenderCommand.lift(try! rustCall {
            uniffi_melan_ffi_fn_method_melanengine_zoom(self.uniffiClonePointer(),
                                                        FfiConverterDouble.lower(factor),
                                                        FfiConverterDouble.lower(focalX),
                                                        FfiConverterDouble.lower(focalY), $0)
        })
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeMelanEngine: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MelanEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MelanEngine {
        return MelanEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MelanEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MelanEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MelanEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeMelanEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> MelanEngine {
    return try FfiConverterTypeMelanEngine.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeMelanEngine_lower(_ value: MelanEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMelanEngine.lower(value)
}

public struct BrushConfig {
    public var brushType: BrushType
    public var color: Color
    public var baseWidth: Double
    public var eraserMode: EraserMode

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(brushType: BrushType, color: Color, baseWidth: Double, eraserMode: EraserMode) {
        self.brushType = brushType
        self.color = color
        self.baseWidth = baseWidth
        self.eraserMode = eraserMode
    }
}

extension BrushConfig: Equatable, Hashable {
    public static func == (lhs: BrushConfig, rhs: BrushConfig) -> Bool {
        if lhs.brushType != rhs.brushType {
            return false
        }
        if lhs.color != rhs.color {
            return false
        }
        if lhs.baseWidth != rhs.baseWidth {
            return false
        }
        if lhs.eraserMode != rhs.eraserMode {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(brushType)
        hasher.combine(color)
        hasher.combine(baseWidth)
        hasher.combine(eraserMode)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeBrushConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BrushConfig {
        return
            try BrushConfig(
                brushType: FfiConverterTypeBrushType.read(from: &buf),
                color: FfiConverterTypeColor.read(from: &buf),
                baseWidth: FfiConverterDouble.read(from: &buf),
                eraserMode: FfiConverterTypeEraserMode.read(from: &buf)
            )
    }

    public static func write(_ value: BrushConfig, into buf: inout [UInt8]) {
        FfiConverterTypeBrushType.write(value.brushType, into: &buf)
        FfiConverterTypeColor.write(value.color, into: &buf)
        FfiConverterDouble.write(value.baseWidth, into: &buf)
        FfiConverterTypeEraserMode.write(value.eraserMode, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeBrushConfig_lift(_ buf: RustBuffer) throws -> BrushConfig {
    return try FfiConverterTypeBrushConfig.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeBrushConfig_lower(_ value: BrushConfig) -> RustBuffer {
    return FfiConverterTypeBrushConfig.lower(value)
}

public struct CanvasSize {
    public var width: Double
    public var height: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(width: Double, height: Double) {
        self.width = width
        self.height = height
    }
}

extension CanvasSize: Equatable, Hashable {
    public static func == (lhs: CanvasSize, rhs: CanvasSize) -> Bool {
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(width)
        hasher.combine(height)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeCanvasSize: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CanvasSize {
        return
            try CanvasSize(
                width: FfiConverterDouble.read(from: &buf),
                height: FfiConverterDouble.read(from: &buf)
            )
    }

    public static func write(_ value: CanvasSize, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.width, into: &buf)
        FfiConverterDouble.write(value.height, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCanvasSize_lift(_ buf: RustBuffer) throws -> CanvasSize {
    return try FfiConverterTypeCanvasSize.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCanvasSize_lower(_ value: CanvasSize) -> RustBuffer {
    return FfiConverterTypeCanvasSize.lower(value)
}

public struct Color {
    public var r: Float
    public var g: Float
    public var b: Float
    public var a: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(r: Float, g: Float, b: Float, a: Float) {
        self.r = r
        self.g = g
        self.b = b
        self.a = a
    }
}

extension Color: Equatable, Hashable {
    public static func == (lhs: Color, rhs: Color) -> Bool {
        if lhs.r != rhs.r {
            return false
        }
        if lhs.g != rhs.g {
            return false
        }
        if lhs.b != rhs.b {
            return false
        }
        if lhs.a != rhs.a {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(r)
        hasher.combine(g)
        hasher.combine(b)
        hasher.combine(a)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeColor: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Color {
        return
            try Color(
                r: FfiConverterFloat.read(from: &buf),
                g: FfiConverterFloat.read(from: &buf),
                b: FfiConverterFloat.read(from: &buf),
                a: FfiConverterFloat.read(from: &buf)
            )
    }

    public static func write(_ value: Color, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.r, into: &buf)
        FfiConverterFloat.write(value.g, into: &buf)
        FfiConverterFloat.write(value.b, into: &buf)
        FfiConverterFloat.write(value.a, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeColor_lift(_ buf: RustBuffer) throws -> Color {
    return try FfiConverterTypeColor.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeColor_lower(_ value: Color) -> RustBuffer {
    return FfiConverterTypeColor.lower(value)
}

public struct EngineState {
    public var strokeCount: UInt32
    public var canUndo: Bool
    public var canRedo: Bool
    public var scale: Double
    public var offsetX: Double
    public var offsetY: Double
    public var activeLayerId: String
    public var hasSelection: Bool
    public var selectionMinX: Double
    public var selectionMinY: Double
    public var selectionMaxX: Double
    public var selectionMaxY: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(strokeCount: UInt32, canUndo: Bool, canRedo: Bool, scale: Double, offsetX: Double, offsetY: Double, activeLayerId: String, hasSelection: Bool, selectionMinX: Double, selectionMinY: Double, selectionMaxX: Double, selectionMaxY: Double) {
        self.strokeCount = strokeCount
        self.canUndo = canUndo
        self.canRedo = canRedo
        self.scale = scale
        self.offsetX = offsetX
        self.offsetY = offsetY
        self.activeLayerId = activeLayerId
        self.hasSelection = hasSelection
        self.selectionMinX = selectionMinX
        self.selectionMinY = selectionMinY
        self.selectionMaxX = selectionMaxX
        self.selectionMaxY = selectionMaxY
    }
}

extension EngineState: Equatable, Hashable {
    public static func == (lhs: EngineState, rhs: EngineState) -> Bool {
        if lhs.strokeCount != rhs.strokeCount {
            return false
        }
        if lhs.canUndo != rhs.canUndo {
            return false
        }
        if lhs.canRedo != rhs.canRedo {
            return false
        }
        if lhs.scale != rhs.scale {
            return false
        }
        if lhs.offsetX != rhs.offsetX {
            return false
        }
        if lhs.offsetY != rhs.offsetY {
            return false
        }
        if lhs.activeLayerId != rhs.activeLayerId {
            return false
        }
        if lhs.hasSelection != rhs.hasSelection {
            return false
        }
        if lhs.selectionMinX != rhs.selectionMinX {
            return false
        }
        if lhs.selectionMinY != rhs.selectionMinY {
            return false
        }
        if lhs.selectionMaxX != rhs.selectionMaxX {
            return false
        }
        if lhs.selectionMaxY != rhs.selectionMaxY {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(strokeCount)
        hasher.combine(canUndo)
        hasher.combine(canRedo)
        hasher.combine(scale)
        hasher.combine(offsetX)
        hasher.combine(offsetY)
        hasher.combine(activeLayerId)
        hasher.combine(hasSelection)
        hasher.combine(selectionMinX)
        hasher.combine(selectionMinY)
        hasher.combine(selectionMaxX)
        hasher.combine(selectionMaxY)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineState {
        return
            try EngineState(
                strokeCount: FfiConverterUInt32.read(from: &buf),
                canUndo: FfiConverterBool.read(from: &buf),
                canRedo: FfiConverterBool.read(from: &buf),
                scale: FfiConverterDouble.read(from: &buf),
                offsetX: FfiConverterDouble.read(from: &buf),
                offsetY: FfiConverterDouble.read(from: &buf),
                activeLayerId: FfiConverterString.read(from: &buf),
                hasSelection: FfiConverterBool.read(from: &buf),
                selectionMinX: FfiConverterDouble.read(from: &buf),
                selectionMinY: FfiConverterDouble.read(from: &buf),
                selectionMaxX: FfiConverterDouble.read(from: &buf),
                selectionMaxY: FfiConverterDouble.read(from: &buf)
            )
    }

    public static func write(_ value: EngineState, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.strokeCount, into: &buf)
        FfiConverterBool.write(value.canUndo, into: &buf)
        FfiConverterBool.write(value.canRedo, into: &buf)
        FfiConverterDouble.write(value.scale, into: &buf)
        FfiConverterDouble.write(value.offsetX, into: &buf)
        FfiConverterDouble.write(value.offsetY, into: &buf)
        FfiConverterString.write(value.activeLayerId, into: &buf)
        FfiConverterBool.write(value.hasSelection, into: &buf)
        FfiConverterDouble.write(value.selectionMinX, into: &buf)
        FfiConverterDouble.write(value.selectionMinY, into: &buf)
        FfiConverterDouble.write(value.selectionMaxX, into: &buf)
        FfiConverterDouble.write(value.selectionMaxY, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineState_lift(_ buf: RustBuffer) throws -> EngineState {
    return try FfiConverterTypeEngineState.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineState_lower(_ value: EngineState) -> RustBuffer {
    return FfiConverterTypeEngineState.lower(value)
}

public struct FfiPoint {
    public var x: Double
    public var y: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x: Double, y: Double) {
        self.x = x
        self.y = y
    }
}

extension FfiPoint: Equatable, Hashable {
    public static func == (lhs: FfiPoint, rhs: FfiPoint) -> Bool {
        if lhs.x != rhs.x {
            return false
        }
        if lhs.y != rhs.y {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x)
        hasher.combine(y)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPoint: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPoint {
        return
            try FfiPoint(
                x: FfiConverterDouble.read(from: &buf),
                y: FfiConverterDouble.read(from: &buf)
            )
    }

    public static func write(_ value: FfiPoint, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.x, into: &buf)
        FfiConverterDouble.write(value.y, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPoint_lift(_ buf: RustBuffer) throws -> FfiPoint {
    return try FfiConverterTypeFfiPoint.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPoint_lower(_ value: FfiPoint) -> RustBuffer {
    return FfiConverterTypeFfiPoint.lower(value)
}

public struct PathSegment {
    public var p0X: Double
    public var p0Y: Double
    public var cp1X: Double
    public var cp1Y: Double
    public var cp2X: Double
    public var cp2Y: Double
    public var p3X: Double
    public var p3Y: Double
    public var startWidth: Double
    public var endWidth: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(p0X: Double, p0Y: Double, cp1X: Double, cp1Y: Double, cp2X: Double, cp2Y: Double, p3X: Double, p3Y: Double, startWidth: Double, endWidth: Double) {
        self.p0X = p0X
        self.p0Y = p0Y
        self.cp1X = cp1X
        self.cp1Y = cp1Y
        self.cp2X = cp2X
        self.cp2Y = cp2Y
        self.p3X = p3X
        self.p3Y = p3Y
        self.startWidth = startWidth
        self.endWidth = endWidth
    }
}

extension PathSegment: Equatable, Hashable {
    public static func == (lhs: PathSegment, rhs: PathSegment) -> Bool {
        if lhs.p0X != rhs.p0X {
            return false
        }
        if lhs.p0Y != rhs.p0Y {
            return false
        }
        if lhs.cp1X != rhs.cp1X {
            return false
        }
        if lhs.cp1Y != rhs.cp1Y {
            return false
        }
        if lhs.cp2X != rhs.cp2X {
            return false
        }
        if lhs.cp2Y != rhs.cp2Y {
            return false
        }
        if lhs.p3X != rhs.p3X {
            return false
        }
        if lhs.p3Y != rhs.p3Y {
            return false
        }
        if lhs.startWidth != rhs.startWidth {
            return false
        }
        if lhs.endWidth != rhs.endWidth {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(p0X)
        hasher.combine(p0Y)
        hasher.combine(cp1X)
        hasher.combine(cp1Y)
        hasher.combine(cp2X)
        hasher.combine(cp2Y)
        hasher.combine(p3X)
        hasher.combine(p3Y)
        hasher.combine(startWidth)
        hasher.combine(endWidth)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypePathSegment: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PathSegment {
        return
            try PathSegment(
                p0X: FfiConverterDouble.read(from: &buf),
                p0Y: FfiConverterDouble.read(from: &buf),
                cp1X: FfiConverterDouble.read(from: &buf),
                cp1Y: FfiConverterDouble.read(from: &buf),
                cp2X: FfiConverterDouble.read(from: &buf),
                cp2Y: FfiConverterDouble.read(from: &buf),
                p3X: FfiConverterDouble.read(from: &buf),
                p3Y: FfiConverterDouble.read(from: &buf),
                startWidth: FfiConverterDouble.read(from: &buf),
                endWidth: FfiConverterDouble.read(from: &buf)
            )
    }

    public static func write(_ value: PathSegment, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.p0X, into: &buf)
        FfiConverterDouble.write(value.p0Y, into: &buf)
        FfiConverterDouble.write(value.cp1X, into: &buf)
        FfiConverterDouble.write(value.cp1Y, into: &buf)
        FfiConverterDouble.write(value.cp2X, into: &buf)
        FfiConverterDouble.write(value.cp2Y, into: &buf)
        FfiConverterDouble.write(value.p3X, into: &buf)
        FfiConverterDouble.write(value.p3Y, into: &buf)
        FfiConverterDouble.write(value.startWidth, into: &buf)
        FfiConverterDouble.write(value.endWidth, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePathSegment_lift(_ buf: RustBuffer) throws -> PathSegment {
    return try FfiConverterTypePathSegment.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePathSegment_lower(_ value: PathSegment) -> RustBuffer {
    return FfiConverterTypePathSegment.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum BrushType {
    case pen
    case highlighter
    case eraser
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeBrushType: FfiConverterRustBuffer {
    typealias SwiftType = BrushType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BrushType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .pen

        case 2: return .highlighter

        case 3: return .eraser

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BrushType, into buf: inout [UInt8]) {
        switch value {
        case .pen:
            writeInt(&buf, Int32(1))

        case .highlighter:
            writeInt(&buf, Int32(2))

        case .eraser:
            writeInt(&buf, Int32(3))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeBrushType_lift(_ buf: RustBuffer) throws -> BrushType {
    return try FfiConverterTypeBrushType.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeBrushType_lower(_ value: BrushType) -> RustBuffer {
    return FfiConverterTypeBrushType.lower(value)
}

extension BrushType: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum EraserMode {
    case stroke
    case partial
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeEraserMode: FfiConverterRustBuffer {
    typealias SwiftType = EraserMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EraserMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .stroke

        case 2: return .partial

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EraserMode, into buf: inout [UInt8]) {
        switch value {
        case .stroke:
            writeInt(&buf, Int32(1))

        case .partial:
            writeInt(&buf, Int32(2))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEraserMode_lift(_ buf: RustBuffer) throws -> EraserMode {
    return try FfiConverterTypeEraserMode.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEraserMode_lower(_ value: EraserMode) -> RustBuffer {
    return FfiConverterTypeEraserMode.lower(value)
}

extension EraserMode: Equatable, Hashable {}

public enum MelanCoreError {
    case FormatError(msg: String
    )
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeMelanCoreError: FfiConverterRustBuffer {
    typealias SwiftType = MelanCoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MelanCoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .FormatError(
                msg: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MelanCoreError, into buf: inout [UInt8]) {
        switch value {
        case let .FormatError(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
        }
    }
}

extension MelanCoreError: Equatable, Hashable {}

extension MelanCoreError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum RenderCommand {
    case clear(r: Float, g: Float, b: Float, a: Float)
    case saveState
    case restoreState
    case setTransform(scale: Double, translateX: Double, translateY: Double)
    case drawVariableWidthPath(segments: [PathSegment], r: Float, g: Float, b: Float, a: Float, isEraser: Bool)
    case drawClosedPath(points: [FfiPoint], r: Float, g: Float, b: Float, a: Float, lineWidth: Double)
    case drawRect(minX: Double, minY: Double, maxX: Double, maxY: Double, r: Float, g: Float, b: Float, a: Float, lineWidth: Double)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeRenderCommand: FfiConverterRustBuffer {
    typealias SwiftType = RenderCommand

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RenderCommand {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .clear(r: FfiConverterFloat.read(from: &buf), g: FfiConverterFloat.read(from: &buf), b: FfiConverterFloat.read(from: &buf), a: FfiConverterFloat.read(from: &buf))

        case 2: return .saveState

        case 3: return .restoreState

        case 4: return try .setTransform(scale: FfiConverterDouble.read(from: &buf), translateX: FfiConverterDouble.read(from: &buf), translateY: FfiConverterDouble.read(from: &buf))

        case 5: return try .drawVariableWidthPath(segments: FfiConverterSequenceTypePathSegment.read(from: &buf), r: FfiConverterFloat.read(from: &buf), g: FfiConverterFloat.read(from: &buf), b: FfiConverterFloat.read(from: &buf), a: FfiConverterFloat.read(from: &buf), isEraser: FfiConverterBool.read(from: &buf))

        case 6: return try .drawClosedPath(points: FfiConverterSequenceTypeFfiPoint.read(from: &buf), r: FfiConverterFloat.read(from: &buf), g: FfiConverterFloat.read(from: &buf), b: FfiConverterFloat.read(from: &buf), a: FfiConverterFloat.read(from: &buf), lineWidth: FfiConverterDouble.read(from: &buf))

        case 7: return try .drawRect(minX: FfiConverterDouble.read(from: &buf), minY: FfiConverterDouble.read(from: &buf), maxX: FfiConverterDouble.read(from: &buf), maxY: FfiConverterDouble.read(from: &buf), r: FfiConverterFloat.read(from: &buf), g: FfiConverterFloat.read(from: &buf), b: FfiConverterFloat.read(from: &buf), a: FfiConverterFloat.read(from: &buf), lineWidth: FfiConverterDouble.read(from: &buf))

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RenderCommand, into buf: inout [UInt8]) {
        switch value {
        case let .clear(r, g, b, a):
            writeInt(&buf, Int32(1))
            FfiConverterFloat.write(r, into: &buf)
            FfiConverterFloat.write(g, into: &buf)
            FfiConverterFloat.write(b, into: &buf)
            FfiConverterFloat.write(a, into: &buf)

        case .saveState:
            writeInt(&buf, Int32(2))

        case .restoreState:
            writeInt(&buf, Int32(3))

        case let .setTransform(scale, translateX, translateY):
            writeInt(&buf, Int32(4))
            FfiConverterDouble.write(scale, into: &buf)
            FfiConverterDouble.write(translateX, into: &buf)
            FfiConverterDouble.write(translateY, into: &buf)

        case let .drawVariableWidthPath(segments, r, g, b, a, isEraser):
            writeInt(&buf, Int32(5))
            FfiConverterSequenceTypePathSegment.write(segments, into: &buf)
            FfiConverterFloat.write(r, into: &buf)
            FfiConverterFloat.write(g, into: &buf)
            FfiConverterFloat.write(b, into: &buf)
            FfiConverterFloat.write(a, into: &buf)
            FfiConverterBool.write(isEraser, into: &buf)

        case let .drawClosedPath(points, r, g, b, a, lineWidth):
            writeInt(&buf, Int32(6))
            FfiConverterSequenceTypeFfiPoint.write(points, into: &buf)
            FfiConverterFloat.write(r, into: &buf)
            FfiConverterFloat.write(g, into: &buf)
            FfiConverterFloat.write(b, into: &buf)
            FfiConverterFloat.write(a, into: &buf)
            FfiConverterDouble.write(lineWidth, into: &buf)

        case let .drawRect(minX, minY, maxX, maxY, r, g, b, a, lineWidth):
            writeInt(&buf, Int32(7))
            FfiConverterDouble.write(minX, into: &buf)
            FfiConverterDouble.write(minY, into: &buf)
            FfiConverterDouble.write(maxX, into: &buf)
            FfiConverterDouble.write(maxY, into: &buf)
            FfiConverterFloat.write(r, into: &buf)
            FfiConverterFloat.write(g, into: &buf)
            FfiConverterFloat.write(b, into: &buf)
            FfiConverterFloat.write(a, into: &buf)
            FfiConverterDouble.write(lineWidth, into: &buf)
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeRenderCommand_lift(_ buf: RustBuffer) throws -> RenderCommand {
    return try FfiConverterTypeRenderCommand.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeRenderCommand_lower(_ value: RenderCommand) -> RustBuffer {
    return FfiConverterTypeRenderCommand.lower(value)
}

extension RenderCommand: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SaveFormat {
    case json
    case protobuf
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSaveFormat: FfiConverterRustBuffer {
    typealias SwiftType = SaveFormat

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SaveFormat {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .json

        case 2: return .protobuf

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SaveFormat, into buf: inout [UInt8]) {
        switch value {
        case .json:
            writeInt(&buf, Int32(1))

        case .protobuf:
            writeInt(&buf, Int32(2))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSaveFormat_lift(_ buf: RustBuffer) throws -> SaveFormat {
    return try FfiConverterTypeSaveFormat.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSaveFormat_lower(_ value: SaveFormat) -> RustBuffer {
    return FfiConverterTypeSaveFormat.lower(value)
}

extension SaveFormat: Equatable, Hashable {}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeFfiPoint: FfiConverterRustBuffer {
    typealias SwiftType = [FfiPoint]

    public static func write(_ value: [FfiPoint], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiPoint.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiPoint] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiPoint]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeFfiPoint.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypePathSegment: FfiConverterRustBuffer {
    typealias SwiftType = [PathSegment]

    public static func write(_ value: [PathSegment], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePathSegment.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PathSegment] {
        let len: Int32 = try readInt(&buf)
        var seq = [PathSegment]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypePathSegment.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeRenderCommand: FfiConverterRustBuffer {
    typealias SwiftType = [RenderCommand]

    public static func write(_ value: [RenderCommand], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRenderCommand.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RenderCommand] {
        let len: Int32 = try readInt(&buf)
        var seq = [RenderCommand]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeRenderCommand.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_melan_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_add_lasso_point() != 49833 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_add_point() != 21848 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_begin_lasso() != 27637 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_begin_lasso_drag() != 4230 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_begin_stroke() != 21472 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_cancel_lasso() != 27679 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_clear_all() != 12050 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_end_lasso() != 31517 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_end_lasso_drag() != 25809 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_end_stroke() != 59850 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_full_render() != 32801 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_get_state() != 8749 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_has_selection() != 1165 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_lasso_delete() != 43208 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_lasso_duplicate() != 46312 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_load() != 30579 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_pan() != 8129 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_redo() != 62665 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_reset_viewport() != 44645 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_save() != 1130 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_set_brush() != 59865 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_undo() != 51935 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_update_lasso_drag() != 52089 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_method_melanengine_zoom() != 47544 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_constructor_melanengine_new() != 61487 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_melan_ffi_checksum_constructor_melanengine_new_a4() != 39618 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
